/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/MssfgqSskfT
 */
import Link from "next/link"
import { Button } from "@/components/ui/button"
import Image from 'next/image'

export function LandingPage() {
  return (
    (<div>
      <nav className="bg-green-300 dark:bg-green-800 px-6 py-4">
        <div className="flex justify-between items-center">
          <a className="text-2xl font-bold text-gray-800 dark:text-white" href="#">
            Logo
          </a>
          <div className="space-x-4">
            <Link
              className="text-gray-600 dark:text-gray-300 hover:text-gray-800 dark:hover:text-white"
              href="#">
              Home
            </Link>
            <Link
              className="text-gray-600 dark:text-gray-300 hover:text-gray-800 dark:hover:text-white"
              href="#">
              Blog
            </Link>
            <Link
              className="text-gray-600 dark:text-gray-300 hover:text-gray-800 dark:hover:text-white"
              href="#">
              YouTube
            </Link>
          </div>
        </div>
      </nav>
      <section className="w-full py-12 md:py-24 lg:py-32 bg-green-200 dark:bg-green-700">
        <div className="container px-4 md:px-6">
          <div
            className="grid items-center gap-6 lg:grid-cols-[1fr_500px] lg:gap-12 xl:grid-cols-[1fr_550px]">
            <Image
              src="https://tweets-codecademy.s3.eu-central-1.amazonaws.com/cucumber-salad.jpeg"
              alt="Cucumber salad"
              className="mx-auto aspect-video overflow-hidden rounded-xl object-cover object-center sm:w-full lg:order-last"
              width={500}
              height={310}
            />
            <div className="flex flex-col justify-center space-y-4">
              <div className="space-y-2">
                <h2
                  className="text-3xl font-bold tracking-tighter text-gray-800 dark:text-white sm:text-5xl">
                  Cucumber só na salada
                </h2>
                <p
                  className="max-w-[600px] text-gray-700 dark:text-gray-300 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                  Explore opções mais simples para testes de software automatizados, sem a necessidade do uso de
                  cucumber e as palavras-chave Dado/Quando/Então.
                </p>
              </div>
              <div className="flex flex-col gap-2 min-[400px]:flex-row">
                <Link
                  className="inline-flex h-10 items-center justify-center rounded-md bg-gray-900 px-8 text-sm font-medium text-white shadow transition-colors hover:bg-gray-800 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-gray-700 disabled:pointer-events-none disabled:opacity-50 dark:bg-white dark:text-gray-900 dark:hover:bg-gray-200 dark:focus-visible:ring-gray-300"
                  href="#">
                  Saiba mais
                </Link>
                <Link
                  className="inline-flex h-10 items-center justify-center rounded-md border border-gray-200 bg-white px-8 text-sm font-medium shadow-sm transition-colors hover:bg-gray-100 hover:text-gray-800 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-gray-700 disabled:pointer-events-none disabled:opacity-50 dark:border-gray-800 dark:bg-gray-900 dark:hover:bg-gray-800 dark:hover:text-white dark:focus-visible:ring-gray-300"
                  href="#">
                  Comece agora
                </Link>
              </div>
            </div>
          </div>
        </div>
      </section>
      <section className="w-full py-12 md:py-24 lg:py-32 bg-white dark:bg-gray-800">
        <div className="container px-4 md:px-6">
          <h2
            className="text-3xl font-bold tracking-tighter text-gray-800 dark:text-white sm:text-5xl mb-8">
            Alternativas ao Cucumber
          </h2>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
            <div className="bg-gray-100 dark:bg-gray-700 p-6 rounded-lg shadow-md">
              <h3 className="text-xl font-semibold text-gray-800 dark:text-white">Opção 1</h3>
              <p className="mt-2 text-gray-600 dark:text-gray-300">
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod eu lorem et ultricies. In porta
                lorem at dui semper, sit amet ornare nisl ullamcorper.
              </p>
            </div>
            <div className="bg-gray-100 dark:bg-gray-700 p-6 rounded-lg shadow-md">
              <h3 className="text-xl font-semibold text-gray-800 dark:text-white">Opção 2</h3>
              <p className="mt-2 text-gray-600 dark:text-gray-300">
                Aliquam purus sit amet luctus venenatis lectus magna fringilla urna porttitor rhoncus dolor purus non
                enim praesent elementum facilisis leo vel.
              </p>
            </div>
            <div className="bg-gray-100 dark:bg-gray-700 p-6 rounded-lg shadow-md">
              <h3 className="text-xl font-semibold text-gray-800 dark:text-white">Opção 3</h3>
              <p className="mt-2 text-gray-600 dark:text-gray-300">
                Vitae aliquet nec ullamcorper sit amet risus nullam eget felis eget nunc lobortis mattis aliquam
                faucibus purus in massa tempor nec feugiat.
              </p>
            </div>
          </div>
        </div>
      </section>
      <section className="w-full py-12 md:py-24 lg:py-32 bg-green-200 dark:bg-green-700">
        <div className="container px-4 md:px-6">
          <h2
            className="text-3xl font-bold tracking-tighter text-gray-800 dark:text-white sm:text-5xl mb-8">
            Depoimentos de Clientes
          </h2>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
            <div className="bg-gray-100 dark:bg-gray-700 p-6 rounded-lg shadow-md">
              <h3 className="text-xl font-semibold text-gray-800 dark:text-white">Cliente 1</h3>
              <p className="mt-2 text-gray-600 dark:text-gray-300">
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed euismod eu lorem et ultricies. In porta
                lorem at dui semper, sit amet ornare nisl ullamcorper.
              </p>
            </div>
            <div className="bg-gray-100 dark:bg-gray-700 p-6 rounded-lg shadow-md">
              <h3 className="text-xl font-semibold text-gray-800 dark:text-white">Cliente 2</h3>
              <p className="mt-2 text-gray-600 dark:text-gray-300">
                Aliquam purus sit amet luctus venenatis lectus magna fringilla urna porttitor rhoncus dolor purus non
                enim praesent elementum facilisis leo vel.
              </p>
            </div>
            <div className="bg-gray-100 dark:bg-gray-700 p-6 rounded-lg shadow-md">
              <h3 className="text-xl font-semibold text-gray-800 dark:text-white">Cliente 3</h3>
              <p className="mt-2 text-gray-600 dark:text-gray-300">
                Vitae aliquet nec ullamcorper sit amet risus nullam eget felis eget nunc lobortis mattis aliquam
                faucibus purus in massa tempor nec feugiat.
              </p>
            </div>
          </div>
        </div>
      </section>
      <section className="w-full py-12 md:py-24 lg:py-32 bg-white dark:bg-gray-800">
        <div className="container px-4 md:px-6">
          <h2
            className="text-3xl font-bold tracking-tighter text-gray-800 dark:text-white sm:text-5xl mb-8">
            Inscreva-se para receber conteúdos exclusivos
          </h2>
          <form className="flex flex-col md:flex-row gap-4 items-center justify-center">
            <input
              aria-label="Email for subscription"
              className="w-full md:w-auto px-4 py-2 border border-gray-300 rounded-md focus:outline-none focus:border-green-500 dark:bg-gray-700 dark:text-white dark:border-gray-600"
              placeholder="Seu email"
              type="email" />
            <Button
              className="px-8 py-2 rounded-md bg-green-500 hover:bg-green-600 text-white dark:bg-green-400 dark:hover:bg-green-300"
              type="submit"
              variant="default">
              Inscrever
            </Button>
          </form>
        </div>
      </section>
      <footer className="w-full py-4 bg-gray-800 text-center text-white">
        <p>Copyleft 😜 2023 - Talking About Testing</p>
      </footer>
    </div>)
  );
}
